version: "3"
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kowl:
    image: "quay.io/cloudhut/kowl:master"
    network_mode: host
    tty: true
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:9092
    logging:
      driver: none
    depends_on:
    - kafka


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  stream:
    build:
      context: ./
      dockerfile: ./stream/Dockerfile
    tty: true
    environment:
      KAFKA_IP: kafka
      KAFKA_PORT: 9092
      KAFKA_TOPIC: "car_data"
    depends_on:
      - kafka
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "production_status"
        env: "os"
